export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_PR = 'GET_PR'
export const GET_COMMITS = 'GET_COMMITS'
export const GET_REPOSITORIES = 'GET_REPOSITORIES'
export const GET_ISSUES = 'GET_ISSUES'
